openapi: 3.0.1
info:
  title: '@jupiterone/graph-alibaba-cloud'
  description: A graph conversion tool for Alibaba Cloud
  x-cortex-git:
    github:
      repository: JupiterOne/graph-alibaba-cloud
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-tag: '@jupiterone/graph-alibaba-cloud'
  x-cortex-service-groups:
    - tier-4
